GET http://localhost:8082/auth
Content-Type: application/json;charset=UTF-8
Username: pavel
Password: 123456

{}
###


GET http://localhost:8082/forum/topics
Content-Type: application/json
UserId: 2

{
  "themeName": "asdas",
  "text": "sadas"
}
###


POST http://localhost:8082/forum/topics
Content-Type: application/json

{
  "themeName": "asdas",
  "text": "sadas"
}
###

POST http://localhost:8082/texts
Content-Type: application/json
Username: pavel
Password: 123456
Authorization: Bearer e1e71142-f2e5-11e9-a902-04d3b0aac206

{
  "title": "some title",
  "text": "this is a text"
}
###
